spring.application.name=carbontrack

spring.datasource.url=jdbc:mysql://localhost:3306/track
spring.datasource.username=root
spring.datasource.password=Hari@1809
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=true

app.load-sample-data=true

server.port=8081
